# Generated by Django 4.0.1 on 2022-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='contact',
            field=models.BigIntegerField(help_text='Enter Mobile Number'),
        ),
    ]
